version: '3.7'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

  elk:
    container_name: elk
    image: sebp/elk
    restart: always
    ports:
      - 5601:5601
      - 9200:9200 
      - 5044:504

  kfla:
    container_name: kfla
    image: docker.pkg.github.com/putnap/kfla/kfla-app
    environment:
      - DBSettings__ConnectionString=mongodb://mongo:27017
      - ElasticSearch__Uri=http://elk:9200
    depends_on:
      - mongo
      - elk
    ports:
      - 8080:80

volumes:
  mongodb: