name: Docker Image CI

on: 
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        docker build . -f KFLA/Dockerfile -t docker.pkg.github.com/putnap/kfla/kfla-app:${VERSION_NAME}
        docker push docker.pkg.github.com/putnap/kfla/kfla-app:${VERSION_NAME}
      env: 
        VERSION_NAME: ${(date +%s)}
      
