name: Docker Image CI

on: 
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        docker build . --file KFLA/Dockerfile --tag docker.pkg.github.com/putnap/kfla/kfla:$(date +%s)
        docker push docker.pkg.github.com/putnap/kfla/kfla:$(date +%s)
      
